### PR TITLE
Feat/86 newsletter cta content region

### LINKED ISSUE #86: Newsletter CTA Changes - Content Region

### PR DESCRIPTION
**Pull request by rpeterman-gp**
Closes #86 

- Refactors newsletter and CTA fetching and parsing helpers
- Updates Content CTA newsletter sign up forms to be an inline form

## To Review
- [x] Use the Preview link located in the Now comment below.
- [x] Ensure there a is a newsletter CTA setup to be shown in the [Content Pages > Inline End](https://www.pri.org/admin/structure/entityqueue/list/tw_cta_regions_content/subqueues/5/edit?destination=admin/structure/entityqueue/list/tw_cta_regions_content/subqueues) region on live.

>  ...or...

- [ ] Ensure there a is a newsletter CTA setup to be shown in the [Content Pages > Inline End](https://pri9.lndo.site/admin/structure/entityqueue/list/tw_cta_regions_content/subqueues/5/edit?destination=admin/structure/entityqueue/list/tw_cta_regions_content/subqueues) region on local dev.
- [ ] Checkout Branch.
- [ ] Run `nvm use`.
- [ ] Run `yarn`.
- [ ] Run `yarn now dev`.
- [ ] Go to [localhost:3000](https://localhost:3000).

>  ...then...
- [x] Visit any story page
- [x] Ensure a newsletter sign up form is shown near at the end of body content
- [x] Ensure the copy shown is that of the CTA message
- [x] Ensure the form signs you up for the configured newsletter list

### CODE REVIEW

**Comment by brandonhundt** [comment]
@rpeterman-gp A few styling thoughts:

Screen Shot 2020-09-22 at 10 34 47 AM

1. Can you remove the <hr>? I think thats one border too many in that box.
2. There's also a lot of extra margin and padding around the terms checkbox. Lets make that a little tighter.

Thanks!!!

**Review by brandonhundt — CHANGES_REQUESTED** [review]
@rpeterman-gp 

1. Go to a story page and scroll to the the inline-end region.
2. Subscribe to the newsletter
3. Subscribe button spins, not subscribed to newsletter.

**Comment by rpeterman-gp** [comment]
@brandonhundt Updated the styling and fixed the subscription endpoint.

**Review by brandonhundt — APPROVED** [review]
:shipit:

**Pull request merged**
