### PR TITLE
#22: Episode pages

### LINKED ISSUE #22: Episode Layout
- Header component
- Episode body data

### PR DESCRIPTION
**Pull request by rpeterman-gp**
Closes #22 

- Adds episode pages

## To Review

- [ ] Use the Preview link located in the Now comment below.

> ...or...

- [x] Checkout Branch.
- [x] Run `yarn`.
- [x] Run `yarn dev:start`.
- [x] Go to [localhost:3000](https://localhost:3000).

> ...then...

- [x] Visit latest episode link.
- [x] Ensure layout and content is rendered as expected.
- [ ] Visit a few other episodes by copying the path from API source site URL's.

### CODE REVIEW

**Review by brandonhundt — COMMENTED** [review]
The h4 'Stories in this episode' is rendered about as twice as large as it probably should be. Maybe try 1.125rem instead of 2.125 rem (Maybe an `<hr>` above the list?)

Otherwise, this is great. Can you remind me when Music Heard on Air will be added? Thanks!!!

**Comment by rpeterman-gp** [comment]
Music heard on air will be added later when I have the data available in the API.

**Comment by rpeterman-gp** [comment]
@brandonhundt Music heard on air section is up, but you have to view it locally with Drupal local dev checked out on PublicRadioInternational/pri.org#1457 branch.

**Review by brandonhundt — APPROVED** [review]
:shipit: Really outstanding work here @rpeterman-gp !!!

**Pull request merged**
